name: Build and Deploy Docker App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t qasim6600/my-chatbot1:latest .

      - name: Push Docker image
        run: docker push qasim6600/my-chatbot1:latest

  deploy-to-azure:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'my-chatbot1'  # Make sure this matches the name in Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'qasim6600/my-chatbot1:latest'
